apiVersion: batch/v1
kind: Job
metadata:
  name: bl46p-example
spec:
  template:
    metadata:
      name: bl46p-example-pod
    spec:
      containers:
      - name: bl46p-example
        image: gcr.io/diamond-privreg/controls/work/ioc/bl46p-ea-ioc-03
      restartPolicy: Never

  
  