apiVersion: apps/v1
kind: Deployment
metadata:
  name: bl46p-example
  labels:
    app: bl46p-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bl46p-example
  template:
    metadata:
      labels:
        app: bl46p-example
    spec:
      containers:
      - name: bl46p-example
        image: gcr.io/diamond-privreg/controls/work/ioc/bl46p-ea-ioc-03:latest
        ports:
        - containerPort: 5064
          protocol: UDP
        - containerPort: 5064
          protocol: TCP
        stdin: true
        tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: bl46p-example-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: bl46p-example


  labels:
    app: bl46p-example

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ca-tcp
      port: 5064
      targetPort: 5064
      protocol: TCP
  selector:
    app: bl46p-example

---
apiVersion: v1
kind: Service
metadata:
  name: bl46p-example-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: bl46p-example


  labels:
    app: bl46p-example

spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: ca-udp
      port: 5064
      targetPort: 5064
      protocol: UDP
  selector:
    app: bl46p-example
  


  